version: '3.9'

services:
  coderace-dev:
    image: maihuuthien/carla-leaderboard:coderace
    container_name: coderace-dev
    network_mode: host
    privileged: true
    environment:
      - DISPLAY=$DISPLAY
      - CARLA_PORT=2000
    command: tail -f /dev/null
    volumes:
      - ./coderace:/workspace/team_code/coderace
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities:
              - gpu
              - utility
              - compute
              - video
